name: Verify Docs

on:
  # pull_request:
  # push:
  #   branches: [ 'main' ]
    
jobs:
  verify-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run docs verification
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          chmod +x ./scripts/verify-docs.sh
          ./scripts/verify-docs.sh
